import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import AppSidebar from '@/components/AppSidebar';
import { getUser } from '@/lib/auth-server';
import Header from '@/components/auth/Header';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-900 w-full h-screen flex overflow-hidden`}
      >
        <SidebarProvider>
          <div className="flex w-full h-full">
            <AppSidebar user={user} />
            <main className="flex-1 h-full overflow-hidden">
              <Header userData={user} />
              {children}
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
